### ISSUE TITLE
Boxart is not downloaded for flashcard games on my device

### ISSUE THREAD

**Issue by chofstede** [Robz8/TWLoader#113]
I have multiple NDS roms on Flashcard inside the 3DS.
The games were successfully added to TWLoader and can be started.

- .INI files are in sdmc:/roms/flashcard/nds and contain the correct TID
- sdmc:/nds/twloader/boxart/ does not contain any file
- sdmc://_nds/twloader/boxart/flashcard does not contain any file

Log-File output in log.ini is this:

```
Method: <WifiStatus> : Message: <Internet connetion active found> 	Additional info:<22:46>
Method: <Download.downloadBoxArt> : Message:<Checking for missing boxart...>
Method: <Download.downloadBoxArt> : Message:<No boxart to download.>
```

The TWLoader Version used is: 3.0.2.

**Comment by Robz8** [comment]
This isn't an issue. All of the box art hasn't been uploaded yet.

**Comment by chofstede** [comment]
Tried ~70 different images from NDS games. PAL/DE and US region.
For the .nds Files, i have on sdmc, I get boxart for some of them. But for
non on the Flashcard. And according to the log.ini, the loader thinks there is nothing to
download "No boxart to download."

Examples tested:  AZEP01, BKIP01 ASMP01

**Comment by Robz8** [comment]
Seems like it's getting the TID incorrectly.

**Comment by Favna** [comment]
Personally build the TWL gui from the latest commit of the repo and I can confirm that box arts are not being downloaded. My situation has been unchanged from when I commented this on #92 but I'll just copypasta what I said in there to here:

My settings.ini:

```
[FRONTEND]
COLOR = 0
TOP_BORDER = 1
TOP_LAYOUT = 0
COUNTER = 0
AUTOUPDATE = 0
AUTODOWNLOAD = 0
ROM_FOLDER = _nds/twloader/roms
FCROM_FOLDER = _nds/twloader/roms
LANGUAGE = -1
MENU_COLOR = 0
SHOW_FILENAME = 0
CUSTOM_BOTTOM = 0
NAME = Favna

[TWL-MODE]
RAINBOW_LED = 0
TWL_CLOCK = 1
BOOT_ANIMATION = 1
HEALTH&SAFETY_MSG = 1
LAUNCH_SLOT1 = 0
RESET_SLOT1 = 1
DEBUG = -1
FORWARDER = 1
FLASHCARD = 2
TWL_VRAM = 1
LOCK_ARM9_SCFG_EXT = 0
SLOT1_KEEPSD = 0
GBARUNNER = 0
GAMESETTINGS_PATH = sd:/_nds/twloader/gamesettings/flashcard/
```

The screen I get when downloading box arts (at launch). After this screen it just moves down out of the screen and it goes to the menu:

![image](https://cloud.githubusercontent.com/assets/4019718/22182429/86c32f86-e0a5-11e6-8f2d-a1c9f340f8c3.png)

Bottom screen when loaded in:

![image](https://cloud.githubusercontent.com/assets/4019718/22182432/9a6e9552-e0a5-11e6-9a04-dea5cbd416aa.png)

Top screen when loaded in:

![image](https://cloud.githubusercontent.com/assets/4019718/22182471/08426004-e0a6-11e6-9255-ab84c20ea627.png)

And lastly my list of games:

![image](https://cloud.githubusercontent.com/assets/4019718/22182440/b7566bfe-e0a5-11e6-8133-50b6bec4f243.png)

**Comment by Jolty95** [comment]
@Favna 
Example: Your rom TID = CQFJ
Boxart is downloaded from http://art.gametdb.com/ds/coverS/EN/CQFJ.png
and page is empty for those TID.

My end: one of my roms TID = CPUS
Boxart page: http://art.gametdb.com/ds/coverS/ES/CPUS.png (ES because I'm spanish and EN doesn't have that boxart)

What I mean is that is not a problem in TWLoader. Is a "problem" with that page that haven't got your boxarts.

**Comment by Favna** [comment]
@Jolty95

Ok that makes a lot of sense for the first one but it is doesn't clarify why after failing on the first it just cancels out and doesn't check the rest. ***that*** is an issue for TWLoader.

**Comment by Jolty95** [comment]
@Favna 
When it fails (I have roms whom boxart doesn't exist in **that** page) it continue reading the boxarts. If I understand you boxarts from flashcard are not working, that's right?
Are you using the old ini files? Or the new inis added from `Add game`?

**Comment by Favna** [comment]
@Jolty95 Added through `add game`. Putting png files in _nds/twloader/boxart/flashcard manually does have them load (picture 1). If only I could determine to which title CQFJ belongs... I tried adding box arts for all tiltes manually in batches of 3 to determine but even after adding them all I still see that error. I cannot find any database for DS titles other than gametdb which doesn't have it either. The next idea I had was to check all the generated ini files and I see nothing remotely close to CQFJ there, but I did notice 1 oddity in the Pokemon White 2 ini file seen in picture 2

![image](https://cloud.githubusercontent.com/assets/4019718/22354200/958bed8c-e424-11e6-907e-f83c92dad4fa.png)


![image](https://cloud.githubusercontent.com/assets/4019718/22354404/7e61dc10-e425-11e6-942c-230541bb0b90.png)

**Comment by Jolty95** [comment]
I can send you a "debug" version to locate CQFJ rom (just print EVERYTHING on log file) if you want.
And about Pokemon White 2... what region is it?

**Comment by Robz8** [comment]
It's US/EU.

**Comment by Jolty95** [comment]
My pokemon white 2 TID is IRDS

**Comment by Robz8** [comment]
The box art for IRDS isn't there.

**Comment by Favna** [comment]
> I can send you a "debug" version to locate CQFJ

Yeah that would help

> It's US/EU.

> IRDS

Interesting coz GameFAQS does list IRDO but not IRDS lol https://www.gamefaqs.com/ds/661227-pokemon-white-version-2/data

**Comment by Jolty95** [comment]
Oh @Favna I think I now why is failing... 
Just a "small" question to be sure. Can you remove the mark  (in English accent mark or acute mark o whatever) I mean replace è with e, and recreate .ini please?

**Comment by Favna** [comment]
> Oh @Favna I think I now why is failing...
Just a "small" question to be sure. Can you remove the mark (in English accent mark or acute mark o whatever) I mean replace è with e, and recreate .ini please?

Didn't do the trick. Also went ahead and removed all `!`'s from the names so the only special character left is a couple of hyphens (`-`)

**Comment by Jolty95** [comment]
I told you to do that because I remember that sometimes when I had flashcard, especial characters where causing troubles.
I think I've fixed. Could you wait a bit more, please? :)

**Comment by Favna** [comment]
Update towards this issue. I installed 3.1 and for some reason i cleared all my previous .ini's, but that did lead me to conclude that the CQFJ error even shows up when I have no ini's whatsoever.

**Comment by Jolty95** [comment]
@Favna sorry, I don't undertand what means "Update towards this issue"
Is still getting errors?

**Comment by Favna** [comment]
Log is available on [hastebin, see here](https://hastebin.com/hitasotuze.xml)

And yes I did mean I am still getting the same error. 

Not sure why you'd per se want me to PM on gbatemp :\ not that I mind tho... so if you really want here is my temp profile:

https://gbatemp.net/members/favna.198047/

**Comment by Jolty95** [comment]
@Favna sorry if that bother you, it wasn't my intention. I said that because I'll send you a debug version and was only for this issue, but if that bother you, I'm sorry.

Download this debug version https://www.dropbox.com/s/93if60bo1gulzyh/TWLoader.cia?dl=1 and send back the log.ini file

**Comment by Favna** [comment]
[Log file](https://hastebin.com/xuquvodaca.xml)

[Settings file](https://hastebin.com/eyurixorud.makefile)

Sending  settings file as well as I noticed it created another entry for the debug version, whether to use debug bootstrap or not.

**Comment by Jolty95** [comment]
shit, settings files was suppose to be a secret until the PR get merge hahah

You are not getting any TID. Are your .ini files good created? I say this because log file should printed `Boxart exist` or `Boxart doesn't exist` and it's because flashcard .ini TID are not correct. Can you show at least 3 or 4 .inis files, please?

**Comment by Favna** [comment]
[rom ini files.zip](https://github.com/Robz8/TWLoader/files/736869/rom.ini.files.zip)

They were all created through "add games", although only Blue Dragon Plus through 3.1 (stable) and the others through 3.0.2. Referencing #128 but as can be seen there I was lucky I backed up previously created ini files :disappointed_relieved: 

ini file location is unchanged from before btw:

![image](https://cloud.githubusercontent.com/assets/4019718/22396515/9a8a7ea6-e55b-11e6-904f-c3690ebab0fb.png)

**Comment by Jolty95** [comment]
Ok, I "know" was is happening

Replace .inis with this, open my debug version and send back the log.ini please

**Comment by Jolty95** [comment]
I'll upload to dropbox cause I cannot attach on github 
https://www.dropbox.com/s/g7n9xiylpzm2sk3/inis.zip?dl=1

**Comment by Favna** [comment]
[Still cannot find the TID](https://hastebin.com/esubuquzuc.xml)

What I also find odd is that it doesn't show a `Method: <TID>` for Bomberman Land Touch :thinking:

**Comment by Jolty95** [comment]
Tid is before name, it's showing fine :)

Can you tell me is this have change?
>[FLASHCARD-ROM]  
>NDS_PATH = Advance Wars Days of Ruin.nds  
>TID = YW2E

**Comment by Favna** [comment]
What I had originally:

```ini
[FLASHCARD-ROM]
NDS_PATH = Advance Wars Days of Ruin.nds
TID = YW2E01
```

What you send me just before:

```ini
[FLASHCARD-ROM]
NDS_PATH = Advance Wars Days of Ruin.nds
TID = YW2E
```

Unchanged after running it:

```ini
[FLASHCARD-ROM]
NDS_PATH = Advance Wars Days of Ruin.nds
TID = YW2E
```

**Comment by Jolty95** [comment]
Roms are loading fine and boxart are display correctly? Just to be sure

**Comment by Favna** [comment]
pre-made box arts show up just fine and games run fine as well. I put in only the box art I have for Advance wars and while doing that also deleted the log so it can be a clean recreated one

[here it is](https://hastebin.com/amobiyifid.xml)

**Comment by Jolty95** [comment]
Don't bother deleting log file. Is cleared every time twloader is run :)
I'll send you a new debug version. This time SHOULD print TID's 

![qr]( http://www.qrcode.es/wp-content/themes/ultra/qrcdr/qrcodes/38b9e5372dd6ec358cba761674a85ca9.png)

**Comment by Favna** [comment]
Yep it found TID's now - but the issue itself is not fixed yet. Still getting the damned CQFJ failure.

As usual, [here is the log file](https://hastebin.com/dazodupite.xml)

**Comment by Jolty95** [comment]
That log has help me a lot. In a couple of minutes I'll send you another qr code. This should stop the CQFJ :)

**Comment by Jolty95** [comment]
I don't have flashcard to test, but I guess this build *should* solve the download problem (and log problem not displaying). 

![qr] (http://www.qrcode.es/wp-content/themes/ultra/qrcdr/qrcodes/38b9e5372dd6ec358cba761674a85ca9.png)

**Comment by Favna** [comment]
Can confirm that it downloaded them. Only Blue Dragon Awakened Shadow is missing out, but then again there is nothing at http://art.gametdb.com/ds/coverS/EN/YBUP.png anyway so that makes sense.

For good measure [here is one more log file](https://hastebin.com/uqowawijay.xml)

**Comment by Jolty95** [comment]
So,...we did it? hahaha
Can you try to add a new rom using Add game? That was causing you issues too. 
Tell me if it's solve and a screenshot of boxart folders and log one more time while I clean up the project to update the PR ;)

**Comment by Favna** [comment]
Did an "add game" for Mario and Luigi Partners in Time

It downloaded box art successfully:

![new](https://cloud.githubusercontent.com/assets/4019718/22397249/de990574-e56d-11e6-95b0-1d5af39df3ab.jpg)

[Log file here](https://hastebin.com/ararizubuh.xml)

Boxart folder (flashcard is empty)

![image](https://cloud.githubusercontent.com/assets/4019718/22397259/052bc0f0-e56e-11e6-8009-72f7341b1844.png)

Ini file that was created through "add game"

```ini
[FLASHCARD-ROM]
NDS_PATH = Mario and Luigi - Partners in Time.nds
TID = ARME01
```

**Comment by Jolty95** [comment]
I think is time to close this and upload commit ;)
Thanks you for helping me debugging. I'll take a look to add game code because is printing garbage on TID (should be ARME not ARM01)

**Comment by Favna** [comment]
Anytime :smile:

**Comment by kamronbatman** [comment]
Looks like TWLoader 6.2 missed Pokemon White (IRAO): http://art.gametdb.com/ds/coverS/US/IRAO.png
